# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9b6fdc005f1692e0beec2538d19330a37a8bbb8002bab574439d3e1e45ff30787e211090d220e6a510209583be631a01df9355f7ccc3853922e60a4c6e0223e
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID_1"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY_1"] %>

test:
  secret_key_base: d62a5c91845aad8ed5800f88ece892f2081c1a83e188b4c2848764867f97a4364aadf8762e4ab963090734581542d9f094e189c6a74eebee20d0699df189ada3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID_1"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY_1"] %>
